stateDiagram-v2
    [*] --> CREATED
    CREATED --> MANIFESTED
    CREATED --> CANCELLED
    MANIFESTED --> CANCELLED

    MANIFESTED --> PARTIALLY_RECEIVED
    MANIFESTED --> RECEIVED

    PARTIALLY_RECEIVED --> RECEIVED
    RECEIVED --> SORTED
    STORED --> READY_FOR_SCHEDULE
    READY_FOR_SCHEDULE --> SCHEDULED
    SCHEDULED --> ASSIGNED
    ASSIGNED --> PICKED_UP
    PICKED_UP --> OUT_FOR_DELIVERY
    OUT_FOR_DELIVERY --> DELIVERED
    OUT_FOR_DELIVERY --> FAILED
    FAILED --> RETURNED_TO_DEPOT
    RETURNED_TO_DEPOT --> READY_FOR_SCHEDULE
    RETURNED_TO_DEPOT --> RETURN_TO_SENDER
    DELIVERED --> COMPLETED
    RETURN_TO_SENDER --> COMPLETED